apiVersion: v1
kind: Service
metadata:
  name: {{ include "hellospringbooteks.fullname" . }}
  labels:
    release: {{ .Values.release.Name }}
    app: {{ .Values.app.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    release: {{ .Values.release.Name }}
    app: {{ .Values.app.Name }}
    slot: {{ .Values.productionSlot }}
